services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "super-secret-key-for-email-project"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /opt/airflow/project/requirements.txt &&
           airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.10.2
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "super-secret-key-for-email-project"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/project
    command: >
      bash -c "pip install -r /opt/airflow/project/requirements.txt &&
              airflow scheduler"

volumes:
  postgres-db-volume:
